name: CI/CD Pipeline for Advanced Tic-Tac-Toe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ qtbase5-dev libqt5sql5 sqlite3 xvfb

    - name: Build the project manually with g++
      run: |
        mkdir -p build
        g++ -o build/AdvancedTicTacToe \
        src/main.cpp src/gamelogic.cpp GUI/gamewindow.cpp GUI/mainwindow.cpp sql_codes/userauth.cpp \
        -I./src -I./GUI -I./sql_codes \
        -lQt5Widgets -lQt5Gui -lQt5Core -lQt5Sql

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ qtbase5-dev libqt5sql5 sqlite3 xvfb

    - name: Build unit tests
      run: |
        mkdir -p build
        g++ -o build/test_gamelogic tests/test_gamelogic.cpp src/gamelogic.cpp -I./src
        g++ -o build/test_ai tests/test_ai.cpp -I./src
        g++ -o build/test_userauth tests/test_userauth.cpp sql_codes/userauth.cpp -I./sql_codes

    - name: Run unit tests
      run: |
        ./build/test_gamelogic
        ./build/test_ai
        ./build/test_userauth

    

