name: Advanced Tic Tac Toe - CI (g++ version)

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake qtbase5-dev qtdeclarative5-dev libqt5sql5-sqlite libsqlite3-dev xvfb

    - name: Create build directory
      run: mkdir -p build

    - name: Configure with CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug

    - name: Build the project
      run: |
        cd build
        make

    - name: Build tests
      run: |
        cd build
        make test_gamelogic

    - name: Run tests
      run: |
        cd build
        ./tests/test_gamelogic

    - name: Run the application with Xvfb
      run: |
        cd build
        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./AdvancedTicTacToe || true

    - name: "CI Result: Passed"
      if: success()
      run: echo "✅ All tests passed."

    - name: "CI Result: Failed"
      if: failure()
      run: echo "❌ One or more tests failed."

