name: C++ CI/CD with Qt

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find Qt include directories (for debugging)
      run: |
        sudo find /usr -name QApplication.h
        sudo find /usr -name QMainWindow.h

    - name: Install Qt and g++
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev qttools5-dev-tools libqt5sql5-sqlite

    - name: Build the main app
      run: |
        mkdir build
        g++ -fPIC -I$(pkg-config --cflags Qt5Core Qt5Gui Qt5Widgets) -o build/AdvancedTicTacToe \
        src/main.cpp src/gamelogic.cpp GUI/gamewindow.cpp GUI/mainwindow.cpp sql_codes/userauth.cpp \
        $(pkg-config --libs Qt5Core Qt5Gui Qt5Widgets)

    - name: Build and run tests
      run: |
        mkdir build_test
        g++ -o build_test/test_gamelogic test/test_gamelogic.cpp src/gamelogic.cpp -I./src
        ./build_test/test_gamelogic

    - name: Ignore Executable folder
      run: echo "Executable/ folder exists only for local .exe version. Skipping..."

    

