name: CI/CD Pipeline for Advanced Tic-Tac-Toe

# Add permissions for the workflow
permissions:
  contents: write  # Required for creating releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Qt 6 and dependencies
    - name: Install Qt 6
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev libqt6sql6-sqlite build-essential

    # Step 3: Configure and build the project
    - name: Build the project
      working-directory: ./TicTacToeApp
      run: |
        qmake6 AdvancedTicTacToe.pro
        make

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Qt 6 and dependencies
    - name: Install Qt 6
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev libqt6sql6-sqlite build-essential

    # Step 3: Configure and build the project (including tests)
    - name: Build the project
      working-directory: ./TicTacToeApp
      run: |
        qmake6 AdvancedTicTacToe.pro CONFIG+=test
        make

    # Step 4: Run the unit tests
    - name: Run unit tests
      working-directory: ./TicTacToeApp
      run: |
        ./TicTacToeTests

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Only deploy on push to main

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install Qt 6 and dependencies
    - name: Install Qt 6
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev qt6-tools-dev libqt6sql6-sqlite build-essential

    # Step 3: Configure and build the project
    - name: Build the project
      working-directory: ./TicTacToeApp
      run: |
        qmake6 AdvancedTicTacToe.pro
        make

    # Step 4: Package the binary
    - name: Package the binary
      working-directory: ./TicTacToeApp
      run: |
        mkdir -p release
        cp AdvancedTicTacToe release/
        tar -czvf advanced-tictactoe-${{ github.sha }}.tar.gz -C release AdvancedTicTacToe

    # Step 5: Create a GitHub Release and upload the artifact
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-${{ github.sha }}
        name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        files: ./TicTacToeApp/advanced-tictactoe-${{ github.sha }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
