name: Advanced Tic Tac Toe - CI (g++ version)

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++ and Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ qtbase5-dev xvfb

    - name: Build the main application
      run: |
        mkdir -p build
        g++ -o build/AdvancedTicTacToe \
        src/main.cpp \
        src/gamelogic.cpp \
        GUI/gamewindow.cpp \
        GUI/mainwindow.cpp \
        sql_codes/userauth.cpp \
        -I./src -I./GUI -I./sql_codes \
        -lQt5Widgets -lQt5Gui -lQt5Core

    - name: Run the game using xvfb
      run: |
        xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./build/AdvancedTicTacToe

    - name: Build test_gamelogic
      run: |
        g++ -o build/test_gamelogic \
        tests/test_gamelogic.cpp \
        src/gamelogic.cpp \
        -I./src

    - name: Run test_gamelogic
      run: ./build/test_gamelogic

    - name: CI Result: ✅ Passed
      if: success()
      run: echo "✅ All tests passed."

    - name: CI Result: ❌ Failed
      if: failure()
      run: echo "❌ One or more tests failed."


    - name: Run test_gamelogic
      run: ./build/test_gamelogic

    - name: Set status check (mark as success)
      if: success()
      run: echo "✅ All tests passed."

    - name: Set status check (mark as failed)
      if: failure()
      run: echo "❌ Tests failed."
